#ifndef REPORTWRITER_H
#define REPORTWRITER_H

#include "../algorithm/RiskAnalysis.h"
#include "../algorithm/FlowNetwork.h"
#include <string>
#include <tuple>
#include <utility>
#include <vector>

/**
 * @brief Writes the assignment result and optional risk analysis to disk.
 * @param outputPath Destination file path.
 * @param assignments Review assignments generated by the flow network.
 * @param missingReviews Submissions whose required reviews were not fully met.
 * @param riskAnalysis Optional result of the single-reviewer failure analysis.
 * @throws std::runtime_error If the output file cannot be opened.
 * @complexity O(A + M + C), where A is the number of assignments, M the number
 * of missing-review entries, and C the number of critical reviewers.
 */
void writeConferenceReport(const std::string& outputPath,
                           const std::vector<ReviewAssignment>& assignments,
                           const std::vector<std::tuple<int, int, int>>& missingReviews,
                           const RiskAnalysisResult* riskAnalysis = nullptr);

#endif //REPORTWRITER_H
