//
// Created by Dário on 05/03/2026.
//

#ifndef DA_CONTROL_H
#define DA_CONTROL_H

#include <string>

/**
 * @brief Stores execution options read from the input file.
 */
struct Control {
    /** @brief Matching mode used when building the flow network. */
    int generateAssignments;
    /** @brief Risk-analysis mode requested by the input instance. */
    int riskAnalysis;
    /** @brief Name of the report file generated by the application. */
    std::string outputFilename = "output.csv";
};

#endif //DA_CONTROL_H
